# Generated by Django 3.0.3 on 2020-02-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maker',
            new_name='Marker',
        ),
    ]
